name: Docker Build Test

# این ربات کی فعال بشه؟
on:
  push:
    branches: [ "main", "famous-dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest  # روی یک لینوکس تازه اجرا شو

    steps:
    # 1. دانلود کد پروژه
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. آماده‌سازی موتور داکر
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. تست بیلد (ساخت ایمیج)
    - name: Test Build Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false  # فعلاً فقط تست کن که ساخته میشه، جایی آپلود نکن
        tags: instastore:test